[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tcp-ip-stack"
version = "2.7.0"
description = "TCP/IP stack written in Python."
readme = "README.md"
authors = [{ name = "Sebastian Majewski", email = "ccie18643@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Development Status :: 3 - Alpha",
    "Operating System :: POSIX :: Linux",
    "Natural Language :: English",
    "Environment :: Console",
    "Topic :: System :: Networking",
    "Typing :: Typed",
]
keywords = ["networking", "tcpip", "stack"]
dependencies = [    
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["testslide", "black", "mypy", "flake8", "codespell", "isort", "pylint", "click"]

[project.urls]
"Homepage" = "https://github.com/ccie18643/PyTCP"
"Bug Tracker" = "https://github.com/ccie18643/PyTCP/issues"

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
src_paths = ["pytcp", "examples", "tests"]
line_length = 80
honor_noqa = true

[tool.codespell]
quiet-level = 2
ignore-words-list = "ect, ether, nd, tha"