################################################################################
##                                                                            ##
##   PyTCP - Python TCP/IP stack                                              ##
##   Copyright (C) 2020-present Sebastian Majewski                            ##
##                                                                            ##
##   This program is free software: you can redistribute it and/or modify     ##
##   it under the terms of the GNU General Public License as published by     ##
##   the Free Software Foundation, either version 3 of the License, or        ##
##   (at your option) any later version.                                      ##
##                                                                            ##
##   This program is distributed in the hope that it will be useful,          ##
##   but WITHOUT ANY WARRANTY; without even the implied warranty of           ##
##   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the             ##
##   GNU General Public License for more details.                             ##
##                                                                            ##
##   You should have received a copy of the GNU General Public License        ##
##   along with this program. If not, see <https://www.gnu.org/licenses/>.    ##
##                                                                            ##
##   Author's email: ccie18643@gmail.com                                      ##
##   Github repository: https://github.com/ccie18643/PyTCP                    ##
##                                                                            ##
################################################################################


"""
This package contains the daemon-backed stdlib-socket drop-in.

'import pytcp.socket as socket' (or 'sys.modules["socket"] = pytcp.socket')
is a one-line stand-in for the standard library's 'socket' module: the
'socket()' factory opens a socket on a running PyTCP daemon and returns a
'Socket' whose data path is a real, selectable descriptor, and the full
stdlib-shaped constant / enum / error / name-resolution surface is
re-exported from the internal 'pytcp.runtime.socket' module so consumers
need no other change. The wrapper and factory live in
'socket__dropin'; this package aggregates them with the re-exported
surface.

pytcp/socket/__init__.py

ver 3.0.8
"""

from pytcp.runtime.socket import (
    AF_INET,
    AF_INET4,
    AF_INET6,
    AF_PACKET,
    ETH_P_ALL,
    ETH_P_ARP,
    ETH_P_IP,
    ETH_P_IPV6,
    INADDR_ANY,
    INADDR_BROADCAST,
    INADDR_LOOPBACK,
    INADDR_NONE,
    IP_ADD_MEMBERSHIP,
    IP_ADD_SOURCE_MEMBERSHIP,
    IP_BLOCK_SOURCE,
    IP_DROP_MEMBERSHIP,
    IP_DROP_SOURCE_MEMBERSHIP,
    IP_MTU,
    IP_OPTIONS,
    IP_RECVERR,
    IP_RECVOPTS,
    IP_RECVTOS,
    IP_RETOPTS,
    IP_TOS,
    IP_TTL,
    IP_UNBLOCK_SOURCE,
    IPPROTO_ICMP,
    IPPROTO_ICMP4,
    IPPROTO_ICMP6,
    IPPROTO_ICMPV6,
    IPPROTO_IP,
    IPPROTO_IP6,
    IPPROTO_IPIP,
    IPPROTO_IPV6,
    IPPROTO_RAW,
    IPPROTO_TCP,
    IPPROTO_UDP,
    IPV6_ADD_MEMBERSHIP,
    IPV6_DROP_MEMBERSHIP,
    IPV6_JOIN_GROUP,
    IPV6_LEAVE_GROUP,
    IPV6_MTU,
    IPV6_RECVERR,
    IPV6_RECVTCLASS,
    IPV6_TCLASS,
    IPV6_UNICAST_HOPS,
    IPV6_V6ONLY,
    MSG_ERRQUEUE,
    MSG_OOB,
    PACKET_BROADCAST,
    PACKET_HOST,
    PACKET_MULTICAST,
    PACKET_OTHERHOST,
    PACKET_OUTGOING,
    SHUT_RD,
    SHUT_RDWR,
    SHUT_WR,
    SO_BINDTODEVICE,
    SO_BROADCAST,
    SO_KEEPALIVE,
    SO_LINGER,
    SO_OOBINLINE,
    SO_RCVBUF,
    SO_RCVTIMEO,
    SO_REUSEADDR,
    SO_REUSEPORT,
    SO_SNDBUF,
    SO_SNDTIMEO,
    SOCK_DGRAM,
    SOCK_RAW,
    SOCK_STREAM,
    SOL_SOCKET,
    SOL_UDP,
    TCP_CONGESTION,
    TCP_FASTOPEN,
    TCP_INFO,
    TCP_KEEPCNT,
    TCP_KEEPIDLE,
    TCP_KEEPINTVL,
    TCP_MAXSEG,
    TCP_NODELAY,
    TCP_USER_TIMEOUT,
    UDP_NO_CHECK6_RX,
    UDP_NO_CHECK6_TX,
    AddressFamily,
    IpOption,
    IpV6Option,
    MsgFlag,
    PacketType,
    ShutdownHow,
    SocketOption,
    SocketType,
    SolLevel,
    SolSocketOption,
    UdpOption,
    gaierror,
    getfqdn,
    gethostbyname_ex,
    gethostname,
    getnameinfo,
)
from pytcp.socket.socket__dropin import (
    Socket,
    create_connection,
    error,
    getaddrinfo,
    gethostbyname,
    has_ipv6,
    socket,
    timeout,
)

__all__ = [
    "AF_INET",
    "AF_INET4",
    "AF_INET6",
    "AF_PACKET",
    "ETH_P_ALL",
    "ETH_P_ARP",
    "ETH_P_IP",
    "ETH_P_IPV6",
    "INADDR_ANY",
    "INADDR_BROADCAST",
    "INADDR_LOOPBACK",
    "INADDR_NONE",
    "IPPROTO_ICMP",
    "IPPROTO_ICMP4",
    "IPPROTO_ICMP6",
    "IPPROTO_ICMPV6",
    "IPPROTO_IP",
    "IPPROTO_IP6",
    "IPPROTO_IPIP",
    "IPPROTO_IPV6",
    "IPPROTO_RAW",
    "IPPROTO_TCP",
    "IPPROTO_UDP",
    "IPV6_ADD_MEMBERSHIP",
    "IPV6_DROP_MEMBERSHIP",
    "IPV6_JOIN_GROUP",
    "IPV6_LEAVE_GROUP",
    "IPV6_MTU",
    "IPV6_RECVERR",
    "IPV6_RECVTCLASS",
    "IPV6_TCLASS",
    "IPV6_UNICAST_HOPS",
    "IPV6_V6ONLY",
    "IP_ADD_MEMBERSHIP",
    "IP_ADD_SOURCE_MEMBERSHIP",
    "IP_BLOCK_SOURCE",
    "IP_DROP_MEMBERSHIP",
    "IP_DROP_SOURCE_MEMBERSHIP",
    "IP_MTU",
    "IP_OPTIONS",
    "IP_RECVERR",
    "IP_RECVOPTS",
    "IP_RECVTOS",
    "IP_RETOPTS",
    "IP_TOS",
    "IP_TTL",
    "IP_UNBLOCK_SOURCE",
    "MSG_ERRQUEUE",
    "MSG_OOB",
    "PACKET_BROADCAST",
    "PACKET_HOST",
    "PACKET_MULTICAST",
    "PACKET_OTHERHOST",
    "PACKET_OUTGOING",
    "SHUT_RD",
    "SHUT_RDWR",
    "SHUT_WR",
    "SOCK_DGRAM",
    "SOCK_RAW",
    "SOCK_STREAM",
    "SOL_SOCKET",
    "SOL_UDP",
    "SO_BINDTODEVICE",
    "SO_BROADCAST",
    "SO_KEEPALIVE",
    "SO_LINGER",
    "SO_OOBINLINE",
    "SO_RCVBUF",
    "SO_RCVTIMEO",
    "SO_REUSEADDR",
    "SO_REUSEPORT",
    "SO_SNDBUF",
    "SO_SNDTIMEO",
    "TCP_CONGESTION",
    "TCP_FASTOPEN",
    "TCP_INFO",
    "TCP_KEEPCNT",
    "TCP_KEEPIDLE",
    "TCP_KEEPINTVL",
    "TCP_MAXSEG",
    "TCP_NODELAY",
    "TCP_USER_TIMEOUT",
    "UDP_NO_CHECK6_RX",
    "UDP_NO_CHECK6_TX",
    "AddressFamily",
    "IpOption",
    "IpV6Option",
    "MsgFlag",
    "PacketType",
    "ShutdownHow",
    "Socket",
    "SocketOption",
    "SocketType",
    "SolLevel",
    "SolSocketOption",
    "UdpOption",
    "create_connection",
    "error",
    "gaierror",
    "getaddrinfo",
    "getfqdn",
    "gethostbyname",
    "gethostbyname_ex",
    "gethostname",
    "getnameinfo",
    "has_ipv6",
    "socket",
    "timeout",
]
