name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: codespell --ignore-words-list="ect,ether,nd,tha" --quiet-level=2 README.md $(find . -name '*.py')
      - run: isort -c --profile black $(find . -name '*.py')
      - run: black --check $(find . -name '*.py')
      - run: flake8 $(find . -name '*.py')
      - run: export MYPYPATH=pytcp && mypy -p pytcp
