name: Publish to PyPi
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check spelling
      run: codespell --ignore-words-list="ect,ether,nd,tha" --quiet-level=2 $(find . -name '*.py')
    - name: Sort includes
      run: isort -c --line-length 80 --profile black $(find . -name '*.py')
    - name: Format code
      run: black --check $(find . -name '*.py')
    - name: Lint
      run: flake8 $(find . -name '*.py')
    - name: Type check
      run: mypy -p pytcp
    - name: Test unit
      run: testslide tests/unit/*.py
    - name: Test integration
      run: testslide tests/integration/*.py
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN__PYTCP }}
